# Generated by Django 4.1.5 on 2023-01-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_table'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_likes',
            field=models.ManyToManyField(null=True, related_name='post_image_like', to='users.user'),
        ),
    ]
