# Generated by Django 4.1.5 on 2023-01-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nickname', models.CharField(max_length=24, unique=True)),
                ('name', models.CharField(max_length=24)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_image', models.TextField()),
                ('followers', models.ManyToManyField(to='users.user')),
                ('following', models.ManyToManyField(to='users.user')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
